#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-4 -d I II III IV V
bspc monitor DP-0 -d VI VII VIII IX X
# bspc monitor HDMI-0 -d XX

# Config
bspc config border_width         		2
bspc config window_gap           		6

bspc config split_ratio          		0.6
bspc config borderless_monocle   		false
bspc config gapless_monocle      		false
bspc config pointer_follows_focus 		true
bspc config focus_follows_pointer 		true

bspc config focused_border_color        	"#886cc4"
bspc config normal_border_color         	"#272d38"
bspc config active_border_color         	"#23313D"
bspc config presel_feedback_color		"#748398"

bspc config removal_adjustment			true
bspc config ignore_ewmh_focus			true
bspc config remove_unplugged_monitors		true
bspc config merge_overlapping_monitors		true

# Rules
bspc rule -a brave-browser desktop='^6'
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a discord desktop='^6'

bspc rule -a mpv state=floating
bspc rule -a Yad state=floating
bspc rule -a feh state=floating
bspc rule -a linphone state=floating
bspc rule -a openrgb state=floating
bspc rule -a steam_app_1794680 state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Galculator state=floating

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Reset Screen Layout
autorandr -l 2

# Bar
~/.config/polybar/launch.sh &

# Notifications
# /usr/bin/wired &
dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Picom
picom -b &

# Network Applet
# nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Clipboard Manager
greenclip daemon &

# Run autostart programs
dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &

# Wallpaper
sleep 3 && nitrogen --restore

